### ISSUE TITLE
Eponymous alias hangs dscanner

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [Hackerpilot/dsymbol#3]
```D
struct Foo {}

abstract class Test
{
    protected alias Foo = .Foo;
    protected Foo response;

    private void sendResponse ( )
    {
        with (this.response) {}
    }
}
```

Attaching to the process gives:

```
dsymbol.conversion.second.resolveTypeFromInitializer(dsymbol.symbol.DSymbol*, dsymbol.type_lookup.TypeLookup*, dsymbol.scope_.Scope*, ref dsymbol.modulecache.ModuleCache) (cache=..., moduleScope=0x7f97b36f90f0, lookup=0x7ffe66a24710, symbol=0x7f97b36f9950) at dsymbol/src/dsymbol/conversion/second.d:507
507				|| currentSymbol.kind == CompletionKind.importSymbol
(gdb) bt
#0  dsymbol.conversion.second.resolveTypeFromInitializer(dsymbol.symbol.DSymbol*, dsymbol.type_lookup.TypeLookup*, dsymbol.scope_.Scope*, ref dsymbol.modulecache.ModuleCache) (cache=..., moduleScope=0x7f97b36f90f0, lookup=0x7ffe66a24710, symbol=0x7f97b36f9950) at dsymbol/src/dsymbol/conversion/second.d:507
#1  0x0000000000894667 in dsymbol.conversion.second.resolveType(dsymbol.symbol.DSymbol*, ref containers.unrolledlist.UnrolledList!(dsymbol.type_lookup.TypeLookup*, std.experimental.allocator.mallocator.Mallocator, false, 64uL).UnrolledList, dsymbol.scope_.Scope*, ref dsymbol.modulecache.ModuleCache) (cache=..., 
    moduleScope=0x7f97b36d8950, typeLookups=..., symbol=0x7f97b36d8950) at dsymbol/src/dsymbol/conversion/second.d:418
#2  0x00000000008911e8 in dsymbol.conversion.second.secondPass(dsymbol.semantic.SemanticSymbol*, dsymbol.scope_.Scope*, ref dsymbol.modulecache.ModuleCache) (
    cache=..., moduleScope=0x2a3dee0, currentSymbol=0xb2) at dsymbol/src/dsymbol/conversion/second.d:56
#3  0x00000000008912cd in dsymbol.conversion.second.secondPass(dsymbol.semantic.SemanticSymbol*, dsymbol.scope_.Scope*, ref dsymbol.modulecache.ModuleCache) (
    cache=..., moduleScope=0x0, currentSymbol=0x0) at dsymbol/src/dsymbol/conversion/second.d:77
#4  0x00000000008912cd in dsymbol.conversion.second.secondPass(dsymbol.semantic.SemanticSymbol*, dsymbol.scope_.Scope*, ref dsymbol.modulecache.ModuleCache) (
    cache=..., moduleScope=0x0, currentSymbol=0x0) at dsymbol/src/dsymbol/conversion/second.d:77
#5  0x00000000008912cd in dsymbol.conversion.second.secondPass(dsymbol.semantic.SemanticSymbol*, dsymbol.scope_.Scope*, ref dsymbol.modulecache.ModuleCache) (
    cache=..., moduleScope=0x2, currentSymbol=0x2a4e1d0) at dsymbol/src/dsymbol/conversion/second.d:77
#6  0x00000000009e0a15 in analysis.run.analyze(immutable(char)[], const(dparse.ast.Module), const(analysis.config.StaticAnalysisConfig), ref dsymbol.modulecache.ModuleCache, const(std.experimental.lexer.TokenStructure!(ubyte, "\n    string comment;\n    string trailingComment;\n\n    int opCmp(size_t i) const pure nothrow @safe {\n        if (index < i) return -1;\n        if (index > i) return 1;\n        return 0;\n    }\n\n    int opCmp(ref const typeof(this) other) const pure nothrow @safe {\n        return opCmp(other.index);\n    }\n").TokenStructure)[], bool) (staticAnalyze=35, tokens=..., moduleCache=..., 
    analysisConfig=..., m=0x2a4ca20, fileName=...) at src/analysis/run.d:203
#7  0x00000000009e035b in analysis.run.analyze(immutable(char)[][], const(analysis.config.StaticAnalysisConfig), ref dparse.lexer.StringCache, ref dsymbol.modulecache.ModuleCache, bool) (staticAnalyze=true, moduleCache=..., cache=..., config=..., fileNames=...) at src/analysis/run.d:168
#8  0x00000000009e90c7 in D main (args=...) at src/main.d:196
```

As you can see below, `->type` is `this`:

```
(gdb) p currentSymbol
$1 = (struct dsymbol.symbol.DSymbol *) 0x7f97b36d8560
(gdb) p *currentSymbol
$2 = {parts = {allocator = 0x0, _length = 0, root = 0x0}, name = {data = "Foo"}, callTip = {data = 0x0}, symbolFile = {data = "bug.d"}, doc = {
    data = 0xa5c1ad <_TMP411> ""}, type = 0x7f97b36d8560, argNames = {_back = 0x0, _front = 0x0, _length = 0}, _location = 57, kind = 108 'l', 
  qualifier = 0 '\000', _ownType_skipOver_ = 0 '\000'}
```

**Comment by Hackerpilot** [comment]
I'm not able to reproduce this. It's very likely that I've fixed it while tracking down other bugs.
